### ISSUE TITLE
File names

### ISSUE THREAD

**Issue by nomadnoa** [dvingerh/genshin-audio-exporter#1]
The output file names seem to just input files' name with a number appended. As there are over 10k audio files outputted, it would be very helpful if the actual file names could be found for organising/sorting these.

The names don't seem to be within the pck, and I would appreciate any help in finding/mapping them.

**Comment by dvingerh** [comment]
As far as I'm aware there's no way to determine the original filenames, sorry

**Comment by RabberDakk** [comment]
@dvingerh There seems to be a way to classify file names at the level of character names. I don't know of a specific way to do this..., but can you address this?
https://www.reddit.com/r/Genshin_Impact/comments/u3u7w1/i_was_curious_which_characters_had_the_most_lines/i4za6ev/
