### ISSUE TITLE
Nothing is in the file 

### ISSUE THREAD

**Issue by skaba04** [dvingerh/genshin-audio-exporter#13]
I tried to find those files in the dictionary and nothing was in there. Must i do something to fix this?
![image](https://github.com/dvingerh/genshin-audio-exporter/assets/116293460/b54d2af5-9eb2-4ee8-9332-cac46d96e63b)

**Comment by dvingerh** [comment]
It seems the sound files are stored in a different folder these days. Try checking here:
`D:\Genshin Impact game\GenshinImpact_Data\StreamingAssets\AudioAssets`

**Comment by skaba04** [comment]
ok ok i get it. The problem is that i did not know what voice lines are belong to each charachter or it was like this always?

**Comment by dvingerh** [comment]
There's currently no way to retrieve the original audio names (as far as I am aware), sorry. You'll will have to guess for each file.
I've tried to recover them in the past but failed to do so, more details can be found [**here**](https://github.com/dvingerh/genshin-audio-exporter/issues/6).
