### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by MVDW-Java** [dvingerh/genshin-audio-exporter#14]
Hello, I would love to see having native Linux support for this project.
Running this application under wine doesn't work as it only extracts the WEM file but not the WAV files.
Screenshot of the issue: 
![image](https://github.com/dvingerh/genshin-audio-exporter/assets/22998325/e7206d43-83be-48b0-8bcc-04b67609fa24)

The final output directory is also empty.
Thanks for making this application as it worked fine under Windows :smile: 

(sorry for my bad english, I'm from the Netherlands)

**Comment by dvingerh** [comment]
Mijn project maakt gebruik van libraries die waarschijnlijk niet lekker samenwerken met Wine, er vanuit gaande dat dat de oorzaak is. Een cross-platform versie schrijven is niet iets waar ik de tijd en motivatie voor heb, sorry. Ik zou zelf Windows dual booten of in een VM draaien 'k denk dat dat 't makkelijkste is.
