### ISSUE TITLE
Windows defender and other security vendors detect the program as malicious

### ISSUE THREAD

**Issue by dragongling** [dvingerh/genshin-audio-exporter#2]
Windows defender and 3 other security vendors detect released "[genshin-audio-exporter.exe](https://github.com/dvingerh/genshin-audio-exporter/releases/download/1.1/genshin-audio-exporter.exe)" v. 1.1 as malicious.

[VirusTotal report](https://www.virustotal.com/gui/file/3a1573f04a6879eb0e20fc7dfcf56bf01ec2f509fb9b3682b73716820574a248/detection)

Seems like false positive. What exactly triggers these scanners?

**Comment by dvingerh** [comment]
The executable has other files packed inside for easier distribution. That might trigger it
Otherwise your guess is as good as mine
