### ISSUE TITLE
Allow to [multiple] select .PCK files instead of choosing whole folders

### ISSUE THREAD

**Issue by dragongling** [dvingerh/genshin-audio-exporter#4]
Users may want not the whole dump of Genshin Impact audio, but only some bank from it (only OST, for example, or only some particular bank voices for editing purposes). Manually selecting [multiple] `.PCK` files can save a significant amount of time for them.

**Comment by dvingerh** [comment]
I have opted for OpenFileDialog to allow for selecting individual PCK files. Selecting all files in a directory has the same effect as simply selecting a directory and reading its contents so this should suffice for now. Even though your pull request is no longer needed I thank you for contributing
