### ISSUE TITLE
file names #2

### ISSUE THREAD

**Issue by Roachdaripper** [dvingerh/genshin-audio-exporter#6]
it seems that the tool will very occasionally export a sound file with a filename, is there a possibility you might be able to investigate this further and maybe add support for filename extraction?

![image](https://user-images.githubusercontent.com/11798863/139597633-cb05822f-f488-45ce-b9ae-8589097e44c5.png)

**Comment by dvingerh** [comment]
I've already looked into this, the original names inside the PCK are permanently lost, see the image below
I don't know why some sounds have their filenames intact. But most of them don't have their original names anymore.
  
  
![image](https://user-images.githubusercontent.com/8366383/139752224-a2714c47-f6a7-490c-bef1-2ade69ce375e.png)
