### ISSUE TITLE
Problem compiling program

### ISSUE THREAD

**Issue by Aierrr** [dvingerh/genshin-audio-exporter#7]
I'm trying to help a friend to use this tool by compiling it myself using the Microsoft Framework v3.5; But there seems to be an error when compiling, it redirects me to this:
![image](https://user-images.githubusercontent.com/94765086/142742044-6b6f10f8-1ffc-4aa5-85c9-cdea39eb8858.png)

This is the line of code in Visual Studio for reference.
![image](https://user-images.githubusercontent.com/94765086/142742060-cbd32207-6bec-4fed-bf05-a77a63f232db.png)

No idea what I'm doing wrong, I don't exactly compile programs on a daily basis. Help is appreciated.

**Comment by dvingerh** [comment]
Why would you compile it yourself? There's a binary readily available already here: https://github.com/dvingerh/genshin-audio-exporter/releases/tag/1.2

**Comment by Aierrr** [comment]
Oh well they never really realized there was a compiled one. Thanks for sharing that.
